### ISSUE TITLE
How to test this algorithm on other data sets such as ml-1m?

### ISSUE THREAD

**Issue by familyld** [hexiangnan/sigir16-eals#2]
Hi, Professor He. Recently I'm trying to test e-als on ml-1m and some other data sets, but I'm not so familiar with programming with JAVA. I've preprocessed the data sets in the same form as you shown in the yelp data set. However, without any modification, when I run main_MF.java to test the offline performance, I got an extremely bad result, i.e., 0.4xxx for HR and 0.01xx for NDCG.  This is unacceptable since a simple MF algorithm can have much better performance. Do you have any suggestion about how to reproduce your results? (ml-1m is tested in your paper "Neural Collaborative Filtering" but I can't reproduce the same results) Or do I need to modify some critical parameters?

Thanks. 

Here is the parameters I used:

```
Data	data/ml-1m.rating
#Users	6040
#Items	3706
#Ratings	 994169 (train), 6040(test)
FastALS: showProgress=false, factors=64, maxIter=500, reg=0.010000, w0=10.00, alpha=0.75
```

**Comment by hexiangnan** [comment]
Please be noted that the two papers used different evaluation protocols.

The eALS paper ranks all items during testing.
The NCF paper ranks 99 sampled negatives + 1 positive item.

**Comment by familyld** [comment]
@hexiangnan Thank you for answering.

**Comment by familyld** [comment]
@hexiangnan Hi, Professor He. I've rewritten the code to test eALS in the same way as you mentioned in the NCF paper, i.e., ranks 99 sampled negatives + 1 positive item. Besides, I use ml-1m.train.rating & ml-1m.test.rating & ml-1m.test.negative， which you provided in the neural_collaborative_filtering project. However, the performance of eALS is still not satisfying. For  top-10 recommendation, the best iteration among 50 iterations yields 

```
<iter, hr, ndcg, prec>:	 16	 0.6078	 0.3411	 0.2594, 
```

which is much lower than what you presented in the NCF paper.  The parameter settings is unchanged as:

```
Data	ml-1m
#Users	6040
#Items	3706
#Ratings	 994169 (train), 6040(testPositive), 6040(testNegative)
fastALS: showProgress=false, factors=64, maxIter=50, reg=0.010000, w0=10.00, alpha=0.75
```

Do you have any suggestions to reproduce the results shown in the NCF paper?

Thank you for taking your precious time to read this. Your prompt reply will be highly appreciated.

**Comment by hexiangnan** [comment]
If your implementation is correct, you should tune the hyper-parameters:

alpha=0, 0.2, 0.4, ... 1
w0=10, 20, 40, 80, 160..

I don't remember the optimal settings for this ML dataset.

**Comment by familyld** [comment]
@hexiangnan Thank you.  I'll keep on trying.

**Comment by familyld** [comment]
@hexiangnan Problem solved. Just to remind future visitors of this issue, I tried alpha=0.0 and w0=160 and the model yields:

```
MF_fastALS Best Iteration: <iter, hr, ndcg, prec>:	 39	 0.6978	 0.4242	 0.3393 [00:02:11.766]
```

This is pretty close to the performance that Professor He has presented in the NCF paper.

**Comment by varoon123-coder** [comment]
good evening can you share the code of the evaluation?
